/* AUTO-GENERATED by failprobe/gen_workloads.py — 수정하지 말 것 (재생성됨)
 * workload: fp_c_backup
 * scenario: 백업 서비스: 락 + 파일 매핑 + 워커 프로세스
 * features: lock_flock,mmap_shared,child
 * 계약 v2: A1(named flags)/A2(PHASE+fflush)/A6(핑퐁) 준수. A4는 탐침 목적상 의도적 위반.
 */
#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <mqueue.h>
#include <netinet/in.h>
#include <pthread.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/file.h>
#include <sys/inotify.h>
#include <sys/ipc.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/signalfd.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/timerfd.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#include "flags.h"
#include "probe_server.h"

static void die(const char *m) { perror(m); exit(1); }

static void *g_keep[128]; static int g_keepn;
static int g_keepfd[128]; static int g_keepfdn;
#define KEEP(p)   do { if (g_keepn < 128) g_keep[g_keepn++] = (void *)(p); } while (0)
#define KEEPFD(f) do { if (g_keepfdn < 128) g_keepfd[g_keepfdn++] = (f); } while (0)
#define PHASE(nm) do { printf("PHASE %s\n", nm); fflush(stdout); } while (0)

#define WL_UNUSED __attribute__((unused))
static char *g_base; static size_t g_base_n;
static int g_port WL_UNUSED;
static int g_logfd WL_UNUSED = -1, g_tfd WL_UNUSED = -1, g_usfd WL_UNUSED = -1, g_semid WL_UNUSED = -1;
static char g_path_logfile[128] WL_UNUSED, g_path_fifo[128] WL_UNUSED, g_path_us[96] WL_UNUSED, g_path_watch[128] WL_UNUSED;
static char g_path_shm[128] WL_UNUSED, g_path_mq[128] WL_UNUSED, g_path_map[128] WL_UNUSED, g_path_maps[128] WL_UNUSED;
static char g_path_cwd[128] WL_UNUSED, g_path_flock[128] WL_UNUSED, g_path_plock[128] WL_UNUSED;

static void WL_UNUSED wk_sig_noop(int s) { (void)s; }
static void * WL_UNUSED wk_sleeper(void *a) { (void)a;
    for (;;) { struct timespec ts = { 0, 50000000L }; nanosleep(&ts, NULL); }
    return NULL; }
static pthread_mutex_t g_fx_mu WL_UNUSED = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t g_fx_cv WL_UNUSED = PTHREAD_COND_INITIALIZER;
static void * WL_UNUSED wk_futex_wait(void *a) { (void)a;
    pthread_mutex_lock(&g_fx_mu);
    for (;;) pthread_cond_wait(&g_fx_cv, &g_fx_mu);
    return NULL; }
static long WL_UNUSED now_ms(void) { struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000L + ts.tv_nsec / 1000000L; }

/* -Wall 침묵용: feature 미포함 빌드에서도 공통 심볼을 '사용됨'으로 만든다 */
static __attribute__((used)) void wl_ref_all_(void)
{
    (void)g_keep; (void)g_keepn; (void)g_keepfd; (void)g_keepfdn;
    (void)g_base; (void)g_base_n; (void)g_port;
    (void)g_logfd; (void)g_tfd; (void)g_usfd; (void)g_semid;
    (void)g_path_logfile; (void)g_path_fifo; (void)g_path_us; (void)g_path_watch;
    (void)g_path_shm; (void)g_path_mq; (void)g_path_map; (void)g_path_maps;
    (void)g_path_cwd; (void)g_path_flock; (void)g_path_plock;
    (void)wk_sig_noop; (void)wk_sleeper; (void)wk_futex_wait;
    (void)g_fx_mu; (void)g_fx_cv; (void)now_ms; (void)die;
}

/* phase 관측→freeze 사이 at-or-after 스큐 제거: 각 phase 직후 gap 동안 머물러
 * dump가 "정확히 그 라인 직후 상태"를 얼리게 한다 (호환성 판정 전용 — 시간 측정에는
 * 이 gap이 들어가면 안 되므로 crossover류 측정에 쓸 땐 --phase_gap_ms 0). */
static void phase_gap(long ms)
{
    if (ms <= 0) return;
    struct timespec ts = { ms / 1000, (ms % 1000) * 1000000L };
    nanosleep(&ts, NULL);
}

int main(int argc, char **argv)
{
    long bytes = wl_flag_long(argc, argv, "--bytes", 52428800);
    long port  = wl_flag_long(argc, argv, "--port", 18080);
    long gap_ms = wl_flag_long(argc, argv, "--phase_gap_ms", 400);
    g_port = (int)port;
    PHASE("init"); phase_gap(gap_ms);

    /* base 상주 메모리 (--bytes) */
    if (bytes > 0) {
        g_base = malloc((size_t)bytes); if (!g_base) die("base malloc");
        g_base_n = (size_t)bytes;
        for (size_t i = 0; i < g_base_n; i += 4096) g_base[i] = 1;
    }
    PHASE("base_mem"); phase_gap(gap_ms);

    { snprintf(g_path_flock, sizeof(g_path_flock), "/tmp/criuprobe_flock_p%d", g_port);
    PHASE("f_lock_flock_l01"); phase_gap(gap_ms);
      int fd = open(g_path_flock, O_CREAT | O_RDWR, 0644); if (fd < 0) die("flock open");
      PHASE("f_lock_flock_l02"); phase_gap(gap_ms);
      if (flock(fd, LOCK_EX) < 0) die("flock");
      KEEPFD(fd); }
    PHASE("f_lock_flock"); phase_gap(gap_ms);
    { snprintf(g_path_maps, sizeof(g_path_maps), "/tmp/criuprobe_maps_p%d", g_port);
    PHASE("f_mmap_shared_l01"); phase_gap(gap_ms);
      int fd = open(g_path_maps, O_CREAT | O_RDWR, 0644); if (fd < 0) die("maps open");
      PHASE("f_mmap_shared_l02"); phase_gap(gap_ms);
      size_t n = 8ull << 20; if (ftruncate(fd, n) < 0) die("maps ftruncate");
      PHASE("f_mmap_shared_l03"); phase_gap(gap_ms);
      char *p = mmap(NULL, n, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
      PHASE("f_mmap_shared_l04"); phase_gap(gap_ms);
      if (p == MAP_FAILED) die("maps mmap");
      PHASE("f_mmap_shared_l05"); phase_gap(gap_ms);
      for (size_t i = 0; i < n; i += 4096) p[i] = 6;
      PHASE("f_mmap_shared_l06"); phase_gap(gap_ms);
      KEEP(p); KEEPFD(fd); }
    PHASE("f_mmap_shared"); phase_gap(gap_ms);
    { pid_t c = fork(); if (c < 0) die("fork");
      if (c == 0) { for (;;) { struct timespec ts = { 0, 50000000L }; nanosleep(&ts, NULL); } } }
    PHASE("f_child"); phase_gap(gap_ms);

    int actual_port = 0;
    int lfd = probe_listen((int)port, &actual_port);
    printf("PHASE ready port=%d\n", actual_port); fflush(stdout);

    long t0 = now_ms(); int steady = 0;
    for (;;) {
        probe_serve_pending(lfd, 100);
        { int st; while (waitpid(-1, &st, WNOHANG) > 0) {} }
        if (!steady && now_ms() - t0 > 400) { PHASE("steady"); steady = 1; }
    }
    return 0;
}
