#!/usr/bin/env bash
# env/setup.sh — 환경 setup orchestrator
#
# 호출 순서: hardware/ → policy/ (확장 시)
#
# Usage:  sudo env/setup.sh <run_dir>
#
# 인터페이스: run_dir 하나만 받고, 설정은 <run_dir>/config.env(flattened env,
# config_to_env 산출)에서 CFG_* 변수로 source한다 (스펙 §5-6 — positional 인자 누적 금지).
#
# memory.max는 cgroup의 필수 골격이고, memory.swap.max는 기본 0으로 swap escape를 막는다.
# cpu_bandwidth_cores를 주면 cpu.max를 얹고, cpuset_cpus를 주면 실행 가능한 core 집합도 제한한다.
#
# 주의: hardware/storage.sh, hardware/cpufreq.sh는 run_id로부터 자신의 RUN_DIR을
# ($TESTBED_DIR/runs/<run_id>)를 내부에서 재계산한다(무변경 이식, 검증된 로직). 따라서
# 여기서 받는 <run_dir>은 반드시 $TESTBED_DIR/runs/<run_id>와 같은 경로여야
# storage.env 핸드오프가 맞아떨어진다 — runner/lib/config.sh(Task 9+)가 그 관례로
# run_dir을 만든다.

set -euo pipefail

# 인터페이스: setup.sh <run_dir>   — 설정은 <run_dir>/config.env에서 (스펙 §5-6)
RUN_DIR="${1:?usage: setup.sh <run_dir>}"
# shellcheck source=/dev/null
source "$RUN_DIR/config.env"
RUN_ID="${CFG_RUN_ID:?config.env missing CFG_RUN_ID}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# run_dir 정합성 가드: hardware/storage.sh·cpufreq.sh는 run_id로부터
# $PROJECT_ROOT/runs/$run_id를 자체 재계산한다. 경로가 어긋나면 storage.env
# 핸드오프 실패(중간 크래시·cgroup 누수) 또는 teardown의 침묵 부분정리가 생기므로
# mutation 전에 크게 실패한다.
CANON_RUN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)/runs/$RUN_ID"
if [[ "$(cd "$RUN_DIR" && pwd)" != "$CANON_RUN_DIR" ]]; then
	echo "ERROR: run_dir '$RUN_DIR' != canonical '$CANON_RUN_DIR' (hardware 모듈이 run_id로 경로를 재계산함)" >&2
	exit 1
fi

MEMORY_MAX="${CFG_MEMORY_MAX:?config.env missing CFG_MEMORY_MAX}"
MEMORY_SWAP_MAX="${CFG_MEMORY_SWAP_MAX:-0}"
CPU_BANDWIDTH_CORES="${CFG_CPU_BANDWIDTH_CORES:-}"
CPUSET_CPUS="${CFG_CPUSET_CPUS:-}"
# cpu 주파수 고정(선택). 비면 미적용. 주면 호스트 전역 DVFS라 teardown이 반드시 원복한다.
CPU_FREQ_KHZ="${CFG_CPU_FREQ_KHZ:-}"
STORAGE_IMAGE_ENABLED="${CFG_STORAGE_IMAGE_ENABLED:-false}"
STORAGE_IMAGE_CAPACITY="${CFG_STORAGE_IMAGE_CAPACITY:-256M}"
STORAGE_IMAGE_RBPS="${CFG_STORAGE_IMAGE_RBPS:-max}"
STORAGE_IMAGE_WBPS="${CFG_STORAGE_IMAGE_WBPS:-max}"
STORAGE_IMAGE_DELAY_ENABLED="${CFG_STORAGE_IMAGE_DELAY_ENABLED:-false}"
STORAGE_IMAGE_DELAY_READ_MS="${CFG_STORAGE_IMAGE_DELAY_READ_MS:-0}"
STORAGE_IMAGE_DELAY_WRITE_MS="${CFG_STORAGE_IMAGE_DELAY_WRITE_MS:-0}"

mkdir -p "$RUN_DIR"

echo "[env/setup] === run_id=$RUN_ID ==="

# --- 1. hardware (물리적 제약) ---
# 1a. cgroup 골격 생성
"$SCRIPT_DIR/hardware/cgroup.sh" create "$RUN_ID"
# 1b. memory 제약 (필수) — swap은 기본 0으로 막고, 필요할 때만 작은 값으로 연다.
"$SCRIPT_DIR/hardware/memory.sh" apply "$RUN_ID" "$MEMORY_MAX" "$MEMORY_SWAP_MAX"
# 1c. cpu 제약 (선택) — bandwidth 또는 cpuset 중 하나라도 주면 cpu.sh가 담당
if [[ -n "$CPU_BANDWIDTH_CORES" || -n "$CPUSET_CPUS" ]]; then
	"$SCRIPT_DIR/hardware/cpu.sh" apply "$RUN_ID" "${CPU_BANDWIDTH_CORES:-max}" "$CPUSET_CPUS"
fi
# 1c2. cpu 주파수 고정 (선택) — 호스트 전역 DVFS clamp. cpuset 코어를 목표 클럭에 박는다.
#      cgroup 밖 상태라 teardown(hardware/cpufreq.sh restore)이 반드시 원복한다. cpuset 필수.
if [[ -n "$CPU_FREQ_KHZ" && "$CPU_FREQ_KHZ" != "none" && "$CPU_FREQ_KHZ" != "max" ]]; then
	"$SCRIPT_DIR/hardware/cpufreq.sh" apply "$RUN_ID" "$CPU_FREQ_KHZ" "$CPUSET_CPUS"
fi

# 1d. storage 제약 (선택) — CRIU image 저장소 capacity/io.max
"$SCRIPT_DIR/hardware/storage.sh" apply "$RUN_ID" "$STORAGE_IMAGE_ENABLED" "$STORAGE_IMAGE_CAPACITY" \
	"$STORAGE_IMAGE_RBPS" "$STORAGE_IMAGE_WBPS" "$STORAGE_IMAGE_DELAY_ENABLED" \
	"$STORAGE_IMAGE_DELAY_READ_MS" "$STORAGE_IMAGE_DELAY_WRITE_MS"
# shellcheck source=/dev/null
source "$RUN_DIR/storage.env"

# --- 2. policy (OS 정책) — TODO ---
# "$SCRIPT_DIR/policy/sysctl.sh" apply "$RUN_ID" "<profile>"
# "$SCRIPT_DIR/policy/swap.sh"   apply "$RUN_ID" "<backend>"

# --- 3. state file ---
cat > "$RUN_DIR/state.env" <<EOF
# generated by env/setup.sh at $(date -Iseconds)
RUN_ID=$RUN_ID
CG_PATH=/sys/fs/cgroup/criu_test_$RUN_ID
IMAGE_DIR=$IMAGE_DIR
MEMORY_MAX=$MEMORY_MAX
MEMORY_SWAP_MAX=$MEMORY_SWAP_MAX
CPU_BANDWIDTH_CORES=${CPU_BANDWIDTH_CORES:-}
CPU_CORES=${CPU_BANDWIDTH_CORES:-}
CPUSET_CPUS=${CPUSET_CPUS:-}
CPU_FREQ_KHZ=${CPU_FREQ_KHZ:-}
STORAGE_IMAGE_ENABLED=$STORAGE_IMAGE_ENABLED
STORAGE_IMAGE_CAPACITY=$STORAGE_IMAGE_CAPACITY
STORAGE_IMAGE_RBPS=$STORAGE_IMAGE_RBPS
STORAGE_IMAGE_WBPS=$STORAGE_IMAGE_WBPS
STORAGE_IMAGE_DELAY_ENABLED=$STORAGE_IMAGE_DELAY_ENABLED
STORAGE_IMAGE_DELAY_READ_MS=$STORAGE_IMAGE_DELAY_READ_MS
STORAGE_IMAGE_DELAY_WRITE_MS=$STORAGE_IMAGE_DELAY_WRITE_MS
STORAGE_IMAGE_LOOP=${STORAGE_IMAGE_LOOP:-}
STORAGE_IMAGE_LOOP_MAJMIN=${STORAGE_IMAGE_LOOP_MAJMIN:-}
STORAGE_IMAGE_DATA_DEV=${STORAGE_IMAGE_DATA_DEV:-}
STORAGE_IMAGE_MAJMIN=${STORAGE_IMAGE_MAJMIN:-}
STORAGE_IMAGE_DM_NAME=${STORAGE_IMAGE_DM_NAME:-}
STORAGE_IMAGE_DM_DEV=${STORAGE_IMAGE_DM_DEV:-}
STORAGE_IMAGE_BACKING=${STORAGE_IMAGE_BACKING:-}
KERNEL_VERSION=$(uname -r)
EOF

echo "[env/setup] state: $RUN_DIR/state.env"
echo "[env/setup] DONE"
