/* AUTO-GENERATED by failprobe/gen_workloads.py — 수정하지 말 것 (재생성됨)
 * workload: fp_w_devmode_console
 * scenario: [R] webOS-faithful: 개발자 모드 진단 도구 — 셸 상속 ctty (클러스터 ③의 B급 맥락 재현)
 * features: tty,pipe,unix_conn
 * 계약 v2: A1(named flags)/A2(PHASE+fflush)/A6(핑퐁) 준수. A4는 탐침 목적상 의도적 위반.
 */
#define _GNU_SOURCE
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <mqueue.h>
#include <netinet/in.h>
#include <pthread.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/file.h>
#include <sys/inotify.h>
#include <sys/ipc.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <sys/signalfd.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/timerfd.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>
#include "flags.h"
#include "probe_server.h"

static void die(const char *m) { perror(m); exit(1); }

static void *g_keep[128]; static int g_keepn;
static int g_keepfd[128]; static int g_keepfdn;
#define KEEP(p)   do { if (g_keepn < 128) g_keep[g_keepn++] = (void *)(p); } while (0)
#define KEEPFD(f) do { if (g_keepfdn < 128) g_keepfd[g_keepfdn++] = (f); } while (0)
#define PHASE(nm) do { printf("PHASE %s\n", nm); fflush(stdout); } while (0)

#define WL_UNUSED __attribute__((unused))
static char *g_base; static size_t g_base_n;
static int g_port WL_UNUSED;
static int g_logfd WL_UNUSED = -1, g_tfd WL_UNUSED = -1, g_usfd WL_UNUSED = -1, g_semid WL_UNUSED = -1;
static char g_path_logfile[128] WL_UNUSED, g_path_fifo[128] WL_UNUSED, g_path_us[96] WL_UNUSED, g_path_watch[128] WL_UNUSED;
static char g_path_shm[128] WL_UNUSED, g_path_mq[128] WL_UNUSED, g_path_map[128] WL_UNUSED, g_path_maps[128] WL_UNUSED;
static char g_path_cwd[128] WL_UNUSED, g_path_flock[128] WL_UNUSED, g_path_plock[128] WL_UNUSED;

static void WL_UNUSED wk_sig_noop(int s) { (void)s; }
static void * WL_UNUSED wk_sleeper(void *a) { (void)a;
    for (;;) { struct timespec ts = { 0, 50000000L }; nanosleep(&ts, NULL); }
    return NULL; }
static pthread_mutex_t g_fx_mu WL_UNUSED = PTHREAD_MUTEX_INITIALIZER;
static pthread_cond_t g_fx_cv WL_UNUSED = PTHREAD_COND_INITIALIZER;
static void * WL_UNUSED wk_futex_wait(void *a) { (void)a;
    pthread_mutex_lock(&g_fx_mu);
    for (;;) pthread_cond_wait(&g_fx_cv, &g_fx_mu);
    return NULL; }
static long WL_UNUSED now_ms(void) { struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000L + ts.tv_nsec / 1000000L; }

/* -Wall 침묵용: feature 미포함 빌드에서도 공통 심볼을 '사용됨'으로 만든다 */
static __attribute__((used)) void wl_ref_all_(void)
{
    (void)g_keep; (void)g_keepn; (void)g_keepfd; (void)g_keepfdn;
    (void)g_base; (void)g_base_n; (void)g_port;
    (void)g_logfd; (void)g_tfd; (void)g_usfd; (void)g_semid;
    (void)g_path_logfile; (void)g_path_fifo; (void)g_path_us; (void)g_path_watch;
    (void)g_path_shm; (void)g_path_mq; (void)g_path_map; (void)g_path_maps;
    (void)g_path_cwd; (void)g_path_flock; (void)g_path_plock;
    (void)wk_sig_noop; (void)wk_sleeper; (void)wk_futex_wait;
    (void)g_fx_mu; (void)g_fx_cv; (void)now_ms; (void)die;
}

/* phase 관측→freeze 사이 at-or-after 스큐 제거: 각 phase 직후 gap 동안 머물러
 * dump가 "정확히 그 라인 직후 상태"를 얼리게 한다 (호환성 판정 전용 — 시간 측정에는
 * 이 gap이 들어가면 안 되므로 crossover류 측정에 쓸 땐 --phase_gap_ms 0). */
static void phase_gap(long ms)
{
    if (ms <= 0) return;
    struct timespec ts = { ms / 1000, (ms % 1000) * 1000000L };
    nanosleep(&ts, NULL);
}

int main(int argc, char **argv)
{
    long bytes = wl_flag_long(argc, argv, "--bytes", 52428800);
    long port  = wl_flag_long(argc, argv, "--port", 18080);
    long gap_ms = wl_flag_long(argc, argv, "--phase_gap_ms", 400);
    g_port = (int)port;
    PHASE("init"); phase_gap(gap_ms);

    /* base 상주 메모리 (--bytes) */
    if (bytes > 0) {
        g_base = malloc((size_t)bytes); if (!g_base) die("base malloc");
        g_base_n = (size_t)bytes;
        for (size_t i = 0; i < g_base_n; i += 4096) g_base[i] = 1;
    }
    PHASE("base_mem"); phase_gap(gap_ms);

    { int fd = open("/dev/tty", O_RDWR);
    PHASE("f_tty_l01"); phase_gap(gap_ms);
      if (fd >= 0) KEEPFD(fd);
      PHASE("f_tty_l02"); phase_gap(gap_ms);
      printf("PHASE_NOTE tty_open ok=%d errno=%d\n", fd >= 0, fd >= 0 ? 0 : errno);
      PHASE("f_tty_l03"); phase_gap(gap_ms);
      fflush(stdout); }
    PHASE("f_tty"); phase_gap(gap_ms);
    { int p[2]; if (pipe2(p, 0) < 0) die("pipe2");
    PHASE("f_pipe_l01"); phase_gap(gap_ms);
      if (write(p[1], "pending-data\n", 13) != 13) die("pipe write");
      PHASE("f_pipe_l02"); phase_gap(gap_ms);
      KEEPFD(p[0]); KEEPFD(p[1]); }
    PHASE("f_pipe"); phase_gap(gap_ms);
    { if (g_usfd < 0) { /* 자체 리스너가 없으면 하나 만든다 */
        snprintf(g_path_us, sizeof(g_path_us), "/tmp/criuprobe_usc_p%d", g_port);
        unlink(g_path_us);
        g_usfd = socket(AF_UNIX, SOCK_STREAM, 0); if (g_usfd < 0) die("usc socket");
        struct sockaddr_un a; memset(&a, 0, sizeof(a)); a.sun_family = AF_UNIX;
        snprintf(a.sun_path, sizeof(a.sun_path), "%s", g_path_us);
        if (bind(g_usfd, (struct sockaddr *)&a, sizeof(a)) < 0) die("usc bind");
        if (listen(g_usfd, 4) < 0) die("usc listen");
        KEEPFD(g_usfd); }
      int cl = socket(AF_UNIX, SOCK_STREAM, 0); if (cl < 0) die("uconn socket");
      PHASE("f_unix_conn_l01"); phase_gap(gap_ms);
      struct sockaddr_un a; memset(&a, 0, sizeof(a)); a.sun_family = AF_UNIX;
      PHASE("f_unix_conn_l02"); phase_gap(gap_ms);
      snprintf(a.sun_path, sizeof(a.sun_path), "%s", g_path_us);
      PHASE("f_unix_conn_l03"); phase_gap(gap_ms);
      if (connect(cl, (struct sockaddr *)&a, sizeof(a)) < 0) die("uconn connect");
      PHASE("f_unix_conn_l04"); phase_gap(gap_ms);
      int sv = accept(g_usfd, NULL, NULL); if (sv < 0) die("uconn accept");
      PHASE("f_unix_conn_l05"); phase_gap(gap_ms);
      KEEPFD(cl); KEEPFD(sv); }
    PHASE("f_unix_conn"); phase_gap(gap_ms);

    int actual_port = 0;
    int lfd = probe_listen((int)port, &actual_port);
    printf("PHASE ready port=%d\n", actual_port); fflush(stdout);

    long t0 = now_ms(); int steady = 0;
    for (;;) {
        probe_serve_pending(lfd, 100);
        if (!steady && now_ms() - t0 > 400) { PHASE("steady"); steady = 1; }
    }
    return 0;
}
